=== SaraOrtegaHdez13/ordinario-ftw/data/biblioteca.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT biblioteca (canciones, playlists, usuarios)>

<!-- Atributo para el elemento biblioteca -->
<!ATTLIST biblioteca
  version  CDATA  #REQUIRED>

<!ELEMENT canciones (cancion+)>

<!-- Lo que debe de tener cada canción -->
<!ELEMENT cancion (titulo, artista, album, genero, duracion, anio, idioma, calificacion, favorita, portada?, letra?, notas?)>

<!-- A fuerza debe ir el ID, porque con eso se identificará cada
canción para cuando la queramos poner en una playlist-->
<!ATTLIST cancion
  id      ID      #REQUIRED
  estado  (activa | archivada) "activa">

<!ELEMENT titulo      (#PCDATA)>
<!ELEMENT album       (#PCDATA)>
<!ELEMENT duracion    (#PCDATA)>
<!ELEMENT anio        (#PCDATA)>
<!ELEMENT favorita    (#PCDATA)>
<!ELEMENT portada     (#PCDATA)>
<!ELEMENT letra       (#PCDATA)>
<!ELEMENT notas       (#PCDATA)>

<!ELEMENT calificacion (#PCDATA)>
<!ATTLIST calificacion
  estrellas (1 | 2 | 3 | 4 | 5) #REQUIRED>

<!ELEMENT idioma (#PCDATA)>
<!ATTLIST idioma
  codigo (es | en) #REQUIRED>

<!ELEMENT genero (#PCDATA)>
<!ATTLIST genero
  tipo (Balada | Salsa | Cumbia | Videojuegos | PopLatino | Banda | Rock | Bolero | Otro) #REQUIRED>

<!ELEMENT artista (nombre, nacionalidad, generoArtista)>
<!ATTLIST artista
  id CDATA #IMPLIED>

<!ELEMENT nombre          (#PCDATA)>
<!ELEMENT nacionalidad    (#PCDATA)>
<!ELEMENT generoArtista   (#PCDATA)>


<!-- 2da parte, la de las playlist -->
<!ELEMENT playlists (playlist+)>

<!ELEMENT playlist (nombrePlaylist, descripcion?, items)>
<!ATTLIST playlist
  id       ID     #REQUIRED
  publica  (si | no) "no">

<!ELEMENT nombrePlaylist  (#PCDATA)>
<!ELEMENT descripcion     (#PCDATA)>

<!ELEMENT items (item+)>
<!ELEMENT item  (#PCDATA)>

<!-- IDREF es para que el ID que lleve sea existente, que de verdad sea sobre una
canción que ya exista-->
<!ATTLIST item
  refCancion IDREF #REQUIRED
  orden      CDATA #REQUIRED>

=== SaraOrtegaHdez13/ordinario-ftw/data/canciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">

<biblioteca version="1.0">

  <canciones>

    <!-- BALADA -->
    <cancion id="c001" estado="activa">
      <titulo>El Triste</titulo>
      <artista id="a001">
        <nombre>José José</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Balada</generoArtista>
      </artista>
      <album>El Triste</album>
      <genero tipo="Balada">Balada</genero>
      <duracion>3:42</duracion>
      <anio>1970</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <cancion id="c002" estado="activa">
      <titulo>La Incondicional</titulo>
      <artista id="a002">
        <nombre>Luis Miguel</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Balada</generoArtista>
      </artista>
      <album>Será que no me amas</album>
      <genero tipo="Balada">Balada</genero>
      <duracion>4:10</duracion>
      <anio>1989</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <cancion id="c003" estado="activa">
      <titulo>Tan Enamorados</titulo>
      <artista id="a003">
        <nombre>Ricardo Montaner</nombre>
        <nacionalidad>Venezolana</nacionalidad>
        <generoArtista>Balada</generoArtista>
      </artista>
      <album>Tan Enamorados</album>
      <genero tipo="Balada">Balada</genero>
      <duracion>4:05</duracion>
      <anio>1992</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="4">4</calificacion>
      <favorita>false</favorita>
    </cancion>

    <!-- SALSA -->
    <cancion id="c004" estado="activa">
      <titulo>Llorarás</titulo>
      <artista id="a004">
        <nombre>Oscar D'León</nombre>
        <nacionalidad>Venezolana</nacionalidad>
        <generoArtista>Salsa</generoArtista>
      </artista>
      <album>Llorarás</album>
      <genero tipo="Salsa">Salsa</genero>
      <duracion>4:20</duracion>
      <anio>1981</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <cancion id="c005" estado="activa">
      <titulo>Devórame Otra Vez</titulo>
      <artista id="a005">
        <nombre>Lalo Rodríguez</nombre>
        <nacionalidad>Puertorriqueña</nacionalidad>
        <generoArtista>Salsa</generoArtista>
      </artista>
      <album>Devórame Otra Vez</album>
      <genero tipo="Salsa">Salsa</genero>
      <duracion>5:10</duracion>
      <anio>1988</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <cancion id="c006" estado="activa">
      <titulo>La Noche Más Linda</titulo>
      <artista id="a006">
        <nombre>Eddie Santiago</nombre>
        <nacionalidad>Puertorriqueña</nacionalidad>
        <generoArtista>Salsa</generoArtista>
      </artista>
      <album>Sigo Atreviéndome</album>
      <genero tipo="Salsa">Salsa</genero>
      <duracion>4:35</duracion>
      <anio>1989</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="4">4</calificacion>
      <favorita>false</favorita>
    </cancion>

    <!-- CUMBIA -->
    <cancion id="c007" estado="activa">
      <titulo>Perfume de Gardenia</titulo>
      <artista id="a007">
        <nombre>La Sonora Santanera</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Cumbia</generoArtista>
      </artista>
      <album>Perfume de Gardenia</album>
      <genero tipo="Cumbia">Cumbia</genero>
      <duracion>3:30</duracion>
      <anio>1962</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="4">4</calificacion>
      <favorita>false</favorita>
    </cancion>

    <cancion id="c008" estado="activa">
      <titulo>Los Luchadores</titulo>
      <artista id="a007">
        <nombre>La Sonora Santanera</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Cumbia</generoArtista>
      </artista>
      <album>Éxitos de La Sonora</album>
      <genero tipo="Cumbia">Cumbia</genero>
      <duracion>3:15</duracion>
      <anio>1965</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="4">4</calificacion>
      <favorita>false</favorita>
    </cancion>

    <cancion id="c009" estado="activa">
      <titulo>Yo Soy Tu Maestro</titulo>
      <artista id="a009">
        <nombre>Los Télez</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Cumbia</generoArtista>
      </artista>
      <album>Yo Soy Tu Maestro</album>
      <genero tipo="Cumbia">Cumbia</genero>
      <duracion>3:50</duracion>
      <anio>1995</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="3">3</calificacion>
      <favorita>false</favorita>
    </cancion>

    <!-- VIDEOJUEGOS -->
    <cancion id="c010" estado="activa">
      <titulo>Gusty Garden Galaxy</titulo>
      <artista id="a010">
        <nombre>Koji Kondo</nombre>
        <nacionalidad>Japonesa</nacionalidad>
        <generoArtista>Videojuegos</generoArtista>
      </artista>
      <album>Super Mario Galaxy OST</album>
      <genero tipo="Videojuegos">Videojuegos</genero>
      <duracion>3:22</duracion>
      <anio>2007</anio>
      <idioma codigo="en">Inglés</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <cancion id="c011" estado="activa">
      <titulo>Megalovania</titulo>
      <artista id="a011">
        <nombre>Toby Fox</nombre>
        <nacionalidad>Estadounidense</nacionalidad>
        <generoArtista>Videojuegos</generoArtista>
      </artista>
      <album>Undertale OST</album>
      <genero tipo="Videojuegos">Videojuegos</genero>
      <duracion>2:37</duracion>
      <anio>2015</anio>
      <idioma codigo="en">Inglés</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <cancion id="c012" estado="activa">
      <titulo>Canción de Pou</titulo>
      <artista id="a012">
        <nombre>Desconocido</nombre>
        <nacionalidad>Otra</nacionalidad>
        <generoArtista>Videojuegos</generoArtista>
      </artista>
      <album>Pou OST</album>
      <genero tipo="Videojuegos">Videojuegos</genero>
      <duracion>60:00</duracion>
      <anio>2012</anio>
      <idioma codigo="en">Inglés</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
      <notas>1 hora de pura cultura</notas>
    </cancion>

    <!-- BANDA -->
    <cancion id="c013" estado="activa">
      <titulo>Tu Perfume</titulo>
      <artista id="a013">
        <nombre>Banda MS</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Banda</generoArtista>
      </artista>
      <album>Tu Perfume</album>
      <genero tipo="Banda">Banda</genero>
      <duracion>3:48</duracion>
      <anio>2014</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="4">4</calificacion>
      <favorita>false</favorita>
    </cancion>

    <cancion id="c014" estado="activa">
      <titulo>Disponible Para Ti</titulo>
      <artista id="a014">
        <nombre>Banda El Recodo</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Banda</generoArtista>
      </artista>
      <album>Disponible Para Ti</album>
      <genero tipo="Banda">Banda</genero>
      <duracion>3:55</duracion>
      <anio>2010</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="3">3</calificacion>
      <favorita>false</favorita>
    </cancion>

    <cancion id="c015" estado="activa">
      <titulo>Me Vas a Extrañar</titulo>
      <artista id="a013">
        <nombre>Banda MS</nombre>
        <nacionalidad>Mexicana</nacionalidad>
        <generoArtista>Banda</generoArtista>
      </artista>
      <album>Me Vas a Extrañar</album>
      <genero tipo="Banda">Banda</genero>
      <duracion>4:10</duracion>
      <anio>2013</anio>
      <idioma codigo="es">Español</idioma>
      <calificacion estrellas="4">4</calificacion>
      <favorita>false</favorita>
    </cancion>

    <!-- ROCK -->
    <cancion id="c016" estado="activa">
      <titulo>I Was Made for Lovin' You</titulo>
      <artista id="a016">
        <nombre>KISS</nombre>
        <nacionalidad>Estadounidense</nacionalidad>
        <generoArtista>Rock</generoArtista>
      </artista>
      <album>Dynasty</album>
      <genero tipo="Rock">Rock</genero>
      <duracion>4:32</duracion>
      <anio>1979</anio>
      <idioma codigo="en">Inglés</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <cancion id="c017" estado="activa">
      <titulo>Love In Itself</titulo>
      <artista id="a017">
        <nombre>Depeche Mode</nombre>
        <nacionalidad>Británica</nacionalidad>
        <generoArtista>Rock</generoArtista>
      </artista>
      <album>Construction Time Again</album>
      <genero tipo="Rock">Rock</genero>
      <duracion>5:50</duracion>
      <anio>1983</anio>
      <idioma codigo="en">Inglés</idioma>
      <calificacion estrellas="4">4</calificacion>
      <favorita>false</favorita>
    </cancion>

    <cancion id="c018" estado="activa">
      <titulo>Numb</titulo>
      <artista id="a018">
        <nombre>Linkin Park</nombre>
        <nacionalidad>Estadounidense</nacionalidad>
        <generoArtista>Rock</generoArtista>
      </artista>
      <album>Meteora</album>
      <genero tipo="Rock">Rock</genero>
      <duracion>3:05</duracion>
      <anio>2003</anio>
      <idioma codigo="en">Inglés</idioma>
      <calificacion estrellas="5">5</calificacion>
      <favorita>true</favorita>
    </cancion>

    <!-- BOLERO -->
    <cancion id="c019" estado="activa">
      <titulo>Me Odio</titulo>
      <artista id="a019">
